version: '2'
services:
  web:
    build: .
    command: python app/server.py
    ports:
    - "5000:5000"
    volumes:
    - .:/shared
    depends_on:
    - redis
  redis:
     image: redis
     ports:
       - "6379:6379"
